using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Windows;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using YTools.Core;
using YTools.Infrastructure;
using YTools.Models;
using YTools.Services.Storage;

namespace YTools.Services;

public sealed class ClipboardHistoryManager : ObservableObject
{
    private static readonly string[] SensitiveFormats =
    {
        "ExcludeClipboardContentFromMonitorProcessing",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword"
    };

    private static readonly string[] DefaultIgnoredProcesses =
    {
        "1password",
        "bitwarden",
        "keepass",
        "keepassxc",
        "enpass"
    };

    private readonly AppPreferences _preferences;
    private readonly ClipboardPersistenceService _persistence = new();
    private readonly ClipboardMonitor _monitor;
    private readonly DebouncedAction _filterDebouncer = new();
    private readonly Dictionary<Guid, Task<byte[]?>> _imageTasks = [];
    private List<ClipboardHistoryItem> _items = [];
    private List<ClipboardHistoryItem> _filteredItems = [];
    private string _query = "";
    private int _selectedIndex;
    private ClipboardFilter _filter = ClipboardFilter.All;
    private bool _showsClearConfirmation;
    private string? _storageError;
    private bool _isLoading = true;
    private long _storageByteCount;
    private int _persistenceRevision;
    private bool _storageReady;
    private bool _persistenceWritable;
    private int _filterRevision;
    private string _appliedQuery = "";
    private ClipboardFilter _appliedFilter = ClipboardFilter.All;
    private const int MaximumVisibleItems = 100;

    public ClipboardHistoryManager(AppPreferences preferences, ClipboardMonitor monitor)
    {
        _preferences = preferences;
        _monitor = monitor;
        _monitor.Changed += OnClipboardChanged;

        _ = LoadAsync();
        preferences.PropertyChanged += (_, args) =>
        {
            switch (args.PropertyName)
            {
                case nameof(AppPreferences.ClipboardRetentionDays):
                case nameof(AppPreferences.ClipboardMaximumItems):
                    PruneAndPersist();
                    break;
                case nameof(AppPreferences.SearchInputDelay):
                    ScheduleFilter();
                    break;
            }
        };
    }

    public IReadOnlyList<ClipboardHistoryItem> Items => _items;

    public IReadOnlyList<ClipboardHistoryItem> FilteredItems => _filteredItems;

    public string Query
    {
        get => _query;
        set
        {
            if (SetField(ref _query, value))
            {
                if (SelectedIndex != 0)
                {
                    SelectedIndex = 0;
                }

                if (string.IsNullOrWhiteSpace(_query))
                {
                    _filterDebouncer.Cancel();
                    RebuildFilteredItems();
                }
                else
                {
                    ScheduleFilter();
                }
            }
        }
    }

    public int SelectedIndex
    {
        get => _selectedIndex;
        set => SetField(ref _selectedIndex, value);
    }

    public ClipboardFilter Filter
    {
        get => _filter;
        set
        {
            if (SetField(ref _filter, value))
            {
                SelectedIndex = 0;
                _filterDebouncer.Cancel();
                RebuildFilteredItems();
            }
        }
    }

    public bool ShowsClearConfirmation
    {
        get => _showsClearConfirmation;
        set => SetField(ref _showsClearConfirmation, value);
    }

    public string? StorageError
    {
        get => _storageError;
        private set => SetField(ref _storageError, value);
    }

    public bool IsLoading
    {
        get => _isLoading;
        private set => SetField(ref _isLoading, value);
    }

    public long StorageByteCount
    {
        get => _storageByteCount;
        private set => SetField(ref _storageByteCount, value);
    }

    public void PrepareForPresentation()
    {
        Query = "";
        Filter = ClipboardFilter.All;
        SelectedIndex = 0;
        PollPasteboard();
    }

    public bool ClearQuery()
    {
        if (string.IsNullOrEmpty(Query))
        {
            return false;
        }

        Query = "";
        return true;
    }

    public void MoveSelection(int offset)
    {
        EnsureFilterIsCurrent();
        var visible = _filteredItems;
        if (visible.Count == 0)
        {
            return;
        }

        SelectedIndex = (SelectedIndex + offset + visible.Count) % visible.Count;
    }

    public bool CopySelected()
    {
        EnsureFilterIsCurrent();
        if (!_filteredItems.Any() || !_filteredItems.Indices().Contains(SelectedIndex))
        {
            return false;
        }

        Copy(_filteredItems[SelectedIndex]);
        return true;
    }

    public async void Copy(ClipboardHistoryItem item)
    {
        switch (item.Kind)
        {
            case ClipboardItemKind.Text:
                Clipboard.SetText(item.Payload.FirstOrDefault() ?? "");
                break;
            case ClipboardItemKind.Files:
                var collection = new System.Collections.Specialized.StringCollection();
                collection.AddRange(item.Payload.ToArray());
                Clipboard.SetFileDropList(collection);
                break;
            case ClipboardItemKind.Image:
                var data = item.BinaryData ?? await _imageTasks.GetOrAdd(
                    item.Id,
                    id => _persistence.ImageDataAsync(id));
                if (data is not null)
                {
                    Clipboard.SetImage(DecodeImage(data));
                }

                break;
        }
    }

    public void Delete(ClipboardHistoryItem item)
    {
        _items.RemoveAll(existing => existing.Id == item.Id);
        SelectedIndex = Math.Min(SelectedIndex, Math.Max(_filteredItems.Count - 1, 0));
        PersistCurrent();
    }

    public void DeleteSelected()
    {
        EnsureFilterIsCurrent();
        if (!_filteredItems.Any() || !_filteredItems.Indices().Contains(SelectedIndex))
        {
            return;
        }

        Delete(_filteredItems[SelectedIndex]);
    }

    public void TogglePinned(ClipboardHistoryItem item)
    {
        var index = _items.FindIndex(existing => existing.Id == item.Id);
        if (index < 0)
        {
            return;
        }

        _items[index] = item with { IsPinned = !item.IsPinned };
        SortItems();
        PersistCurrent();
    }

    public string? SelectedText
    {
        get
        {
            EnsureFilterIsCurrent();
            if (!_filteredItems.Any()
                || !_filteredItems.Indices().Contains(SelectedIndex)
                || _filteredItems[SelectedIndex].Kind != ClipboardItemKind.Text)
            {
                return null;
            }

            return _filteredItems[SelectedIndex].Payload.FirstOrDefault();
        }
    }

    public void Clear()
    {
        var previous = _items;
        _items = [];
        SelectedIndex = 0;
        _persistenceRevision += 1;
        var revision = _persistenceRevision;
        _persistenceWritable = false;
        _ = ClearAsync(previous, revision);
    }

    public void ClearRecent(int minutes)
    {
        var cutoff = DateTimeOffset.UtcNow.AddMinutes(-minutes);
        _items.RemoveAll(item => item.CreatedAt >= cutoff);
        SelectedIndex = Math.Min(SelectedIndex, Math.Max(_filteredItems.Count - 1, 0));
        PersistCurrent();
    }

    private async Task ClearAsync(List<ClipboardHistoryItem> previous, int revision)
    {
        var (success, error) = await _persistence.ClearAsync(revision);
        if (!success)
        {
            _items = previous;
            _persistenceWritable = false;
            StorageError = $"无法清除剪贴板密文：{error}";
            return;
        }

        _persistenceWritable = true;
        StorageError = null;
        StorageByteCount = 0;
        if (_items.Count > 0)
        {
            PersistCurrent();
        }
    }

    private async Task LoadAsync()
    {
        var result = await _persistence.LoadAsync();
        var byteCount = await _persistence.DiskUsageAsync();
        switch (result.Kind)
        {
            case ClipboardStoreLoadResultKind.Missing:
                _items = [];
                StorageError = null;
                _persistenceWritable = true;
                break;
            case ClipboardStoreLoadResultKind.Loaded:
                _items = result.Items!.Where(item => item.Kind != ClipboardItemKind.Files
                    || item.Payload.All(File.Exists)).ToList();
                StorageError = result.Warning;
                _persistenceWritable = true;
                break;
            default:
                _items = [];
                StorageError = $"{result.Warning} 新记录仅保留在本次运行内存中。";
                _persistenceWritable = false;
                break;
        }

        StorageByteCount = byteCount;
        _storageReady = true;
        IsLoading = false;
        Prune();
        if (_persistenceWritable)
        {
            PersistCurrent();
        }
    }

    private void OnClipboardChanged()
    {
        PollPasteboard();
    }

    private void PollPasteboard()
    {
        if (!_storageReady)
        {
            return;
        }

        if (!_preferences.ClipboardEnabled || _preferences.ClipboardPaused)
        {
            return;
        }

        var capture = MakeCapture();
        if (capture is null)
        {
            return;
        }

        _ = Task.Run(() => ProcessCapture(capture))
            .ContinueWith(task =>
            {
                if (task.IsCompletedSuccessfully && task.Result is { } processed)
                {
                    Ingest(processed);
                }
            }, TaskScheduler.FromCurrentSynchronizationContext());
    }

    private ClipboardCapture? MakeCapture()
    {
        var source = ForegroundProcessName();
        var createdAt = DateTimeOffset.UtcNow;
        var data = Clipboard.GetDataObject();
        if (IsSensitive(data, source))
        {
            return null;
        }

        if (Clipboard.ContainsFileDropList())
        {
            var paths = Clipboard.GetFileDropList().Cast<string>().Take(20).ToList();
            return paths.Count == 0 ? null : ClipboardCapture.Files(paths, source, createdAt);
        }

        if (_preferences.ClipboardStoreImages && Clipboard.ContainsImage())
        {
            try
            {
                var image = Clipboard.GetImage();
                if (image is not null)
                {
                    var png = EncodePng(image);
                    if (png is not null)
                    {
                        return ClipboardCapture.Image(png, source, createdAt);
                    }
                }
            }
            catch
            {
                // Clipboard image formats vary; fall through to text.
            }
        }

        if (Clipboard.ContainsText())
        {
            var text = Clipboard.GetText();
            var policy = new ClipboardTextPolicy(_preferences.ClipboardMaximumTextCharacters);
            return policy.ShouldStore(text) ? ClipboardCapture.Text(text, source, createdAt) : null;
        }

        return null;
    }

    private bool IsSensitive(System.Windows.IDataObject? data, string? sourceProcess)
    {
        if (data is not null)
        {
            foreach (var format in SensitiveFormats)
            {
                if (data.GetDataPresent(format, autoConvert: false))
                {
                    return true;
                }
            }
        }

        var processName = sourceProcess?.ToLowerInvariant() ?? "";
        if (_preferences.ClipboardIgnoredProcessNames.Contains(processName))
        {
            return true;
        }

        return DefaultIgnoredProcesses.Contains(processName);
    }

    private static ProcessedClipboardCapture? ProcessCapture(ClipboardCapture capture)
    {
        const int maximumTextBytes = 1_000_000;
        const int maximumImageBytes = 5_000_000;
        switch (capture.Kind)
        {
            case ClipboardCaptureKind.Files:
                return capture.Paths is { Count: 0 } || capture.Paths is null
                    ? null
                    : new ProcessedClipboardCapture(
                        new ClipboardHistoryItem(
                            Guid.NewGuid(),
                            ClipboardItemKind.Files,
                            capture.Paths,
                            capture.CreatedAt,
                            capture.SourceApplication,
                            ContentHash: Hash(capture.Paths)),
                        null);
            case ClipboardCaptureKind.Text:
                if (capture.Value is null
                    || string.IsNullOrWhiteSpace(capture.Value)
                    || Encoding.UTF8.GetByteCount(capture.Value) > maximumTextBytes)
                {
                    return null;
                }

                return new ProcessedClipboardCapture(
                    new ClipboardHistoryItem(
                        Guid.NewGuid(),
                        ClipboardItemKind.Text,
                        [capture.Value],
                        capture.CreatedAt,
                        capture.SourceApplication,
                        ContentHash: Hash([capture.Value])),
                    null);
            case ClipboardCaptureKind.Image:
                if (capture.PngData is null || capture.PngData.Length > maximumImageBytes)
                {
                    return null;
                }

                var dimensions = ImageDimensions(capture.PngData);
                if (dimensions is null)
                {
                    return null;
                }

                var item = new ClipboardHistoryItem(
                    Guid.NewGuid(),
                    ClipboardItemKind.Image,
                    [$"图片 · {dimensions.Value.Width} × {dimensions.Value.Height}"],
                    capture.CreatedAt,
                    capture.SourceApplication,
                    ContentHash: Hash(capture.PngData));
                return new ProcessedClipboardCapture(item, capture.PngData);
            default:
                return null;
        }
    }

    private void Ingest(ProcessedClipboardCapture processed)
    {
        _items.RemoveAll(item => item.HasSameContent(processed.Item));
        _items.Insert(0, processed.Item);
        SortItems();
        Prune();
        var images = processed.OriginalImage is null
            ? new Dictionary<Guid, byte[]>()
            : new Dictionary<Guid, byte[]> { [processed.Item.Id] = processed.OriginalImage };
        PersistCurrent(images);
    }

    private void PruneAndPersist()
    {
        if (!_storageReady)
        {
            return;
        }

        Prune();
        PersistCurrent();
    }

    private void Prune()
    {
        var cutoff = DateTimeOffset.UtcNow.AddDays(-_preferences.ClipboardRetentionDays);
        _items = _items
            .Where(item => item.IsPinned || item.CreatedAt >= cutoff)
            .Take(_preferences.ClipboardMaximumItems)
            .ToList();
        SelectedIndex = Math.Min(SelectedIndex, Math.Max(_filteredItems.Count - 1, 0));
    }

    private void SortItems()
    {
        _items = _items
            .OrderByDescending(item => item.IsPinned)
            .ThenByDescending(item => item.CreatedAt)
            .ToList();
    }

    private void PersistCurrent(IReadOnlyDictionary<Guid, byte[]>? originalImages = null)
    {
        if (!_storageReady || !_persistenceWritable)
        {
            return;
        }

        _persistenceRevision += 1;
        var revision = _persistenceRevision;
        var snapshot = _items.ToList();
        var images = originalImages ?? new Dictionary<Guid, byte[]>();
        _ = _persistence.PersistAsync(snapshot, images, revision)
            .ContinueWith(async task =>
            {
                if (!task.IsCompletedSuccessfully)
                {
                    return;
                }

                var (success, normalized, error) = task.Result;
                if (normalized is null && success)
                {
                    return;
                }

                if (!success)
                {
                    _persistenceWritable = false;
                    StorageError = $"剪贴板加密存储失败；后续修改仅保留在本次运行内存中：{error}";
                    return;
                }

                var byteCount = await _persistence.DiskUsageAsync();
                if (normalized is not null)
                {
                    _items = normalized;
                }
                StorageByteCount = byteCount;
                StorageError = null;
            }, TaskScheduler.FromCurrentSynchronizationContext());
    }

    private void ScheduleFilter()
    {
        var delayMilliseconds = (int)(_preferences.SearchInputDelay * 1_000);
        _filterDebouncer.Schedule(TimeSpan.FromMilliseconds(delayMilliseconds), RebuildFilteredItems);
    }

    private void EnsureFilterIsCurrent()
    {
        if (_appliedQuery == Query && _appliedFilter == Filter)
        {
            return;
        }

        _filterDebouncer.Cancel();
        _filterRevision += 1;
        var revision = _filterRevision;
        var term = Query.Trim();
        var matches = FilterItems(_items, term, Filter, MaximumVisibleItems);
        ApplyFilteredItems(matches, Query, Filter, revision);
    }

    private void RebuildFilteredItems()
    {
        var term = Query.Trim();
        var requestedQuery = Query;
        var requestedFilter = Filter;
        var snapshot = _items.ToList();
        _filterRevision += 1;
        var revision = _filterRevision;

        if (string.IsNullOrEmpty(term))
        {
            var matches = requestedFilter == ClipboardFilter.All
                ? snapshot.Take(MaximumVisibleItems).ToList()
                : snapshot.Where(item => item.Kind.ToString() == requestedFilter.ToString())
                    .Take(MaximumVisibleItems)
                    .ToList();
            ApplyFilteredItems(matches, requestedQuery, requestedFilter, revision);
            return;
        }

        _ = Task.Run(() => FilterItems(snapshot, term, requestedFilter, MaximumVisibleItems))
            .ContinueWith(task =>
            {
                if (task.IsCompletedSuccessfully)
                {
                    ApplyFilteredItems(task.Result, requestedQuery, requestedFilter, revision);
                }
            }, TaskScheduler.FromCurrentSynchronizationContext());
    }

    private void ApplyFilteredItems(
        List<ClipboardHistoryItem> matches,
        string requestedQuery,
        ClipboardFilter requestedFilter,
        int revision)
    {
        if (revision != _filterRevision || Query != requestedQuery || Filter != requestedFilter)
        {
            return;
        }

        _filteredItems = matches;
        _appliedQuery = requestedQuery;
        _appliedFilter = requestedFilter;
        SelectedIndex = Math.Min(SelectedIndex, Math.Max(matches.Count - 1, 0));
        RaisePropertyChanged(nameof(FilteredItems));
    }

    private static List<ClipboardHistoryItem> FilterItems(
        IReadOnlyList<ClipboardHistoryItem> items,
        string term,
        ClipboardFilter filter,
        int limit)
    {
        var matches = new List<ClipboardHistoryItem>();
        foreach (var item in items)
        {
            var matchesType = filter == ClipboardFilter.All || item.Kind.ToString() == filter.ToString();
            if (!matchesType)
            {
                continue;
            }

            if (!string.IsNullOrEmpty(term)
                && !item.DisplayText.Contains(term, StringComparison.OrdinalIgnoreCase)
                && !(item.SourceApplication?.Contains(term, StringComparison.OrdinalIgnoreCase) ?? false))
            {
                continue;
            }

            matches.Add(item);
            if (matches.Count == limit)
            {
                break;
            }
        }

        return matches;
    }

    private static string? ForegroundProcessName()
    {
        try
        {
            var hwnd = NativeMethods.GetForegroundWindow();
            _ = NativeMethods.GetWindowThreadProcessId(hwnd, out var processId);
            using var process = System.Diagnostics.Process.GetProcessById((int)processId);
            return process.ProcessName;
        }
        catch
        {
            return null;
        }
    }

    private static byte[]? EncodePng(BitmapSource image)
    {
        var encoder = new PngBitmapEncoder();
        encoder.Frames.Add(BitmapFrame.Create(image));
        using var stream = new MemoryStream();
        encoder.Save(stream);
        return stream.ToArray();
    }

    private static BitmapSource DecodeImage(byte[] png)
    {
        using var stream = new MemoryStream(png);
        var decoder = new PngBitmapDecoder(
            stream,
            BitmapCreateOptions.PreservePixelFormat,
            BitmapCacheOption.OnLoad);
        return decoder.Frames[0];
    }

    private static (int Width, int Height)? ImageDimensions(byte[] png)
    {
        try
        {
            using var stream = new MemoryStream(png);
            using var image = System.Drawing.Image.FromStream(stream);
            return (image.Width, image.Height);
        }
        catch
        {
            return null;
        }
    }

    private static string Hash(IReadOnlyList<string> parts)
    {
        return Hash(string.Join("\0", parts));
    }

    private static string Hash(byte[] data)
    {
        return Convert.ToHexString(SHA256.HashData(data)).ToLowerInvariant();
    }

    private static string Hash(string value)
    {
        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
    }
}

public enum ClipboardFilter
{
    All,
    Text,
    Files,
    Image
}

public static class ClipboardFilterMetadata
{
    public static string Title(this ClipboardFilter filter)
    {
        return filter switch
        {
            ClipboardFilter.All => "全部",
            ClipboardFilter.Text => "文本",
            ClipboardFilter.Files => "文件",
            ClipboardFilter.Image => "图片",
            _ => ""
        };
    }
}

internal sealed record ClipboardCapture(
    ClipboardCaptureKind Kind,
    IReadOnlyList<string>? Paths,
    string? Value,
    byte[]? PngData,
    string? SourceApplication,
    DateTimeOffset CreatedAt)
{
    public static ClipboardCapture Files(IReadOnlyList<string> paths, string? source, DateTimeOffset createdAt)
        => new(ClipboardCaptureKind.Files, paths, null, null, source, createdAt);

    public static ClipboardCapture Text(string value, string? source, DateTimeOffset createdAt)
        => new(ClipboardCaptureKind.Text, null, value, null, source, createdAt);

    public static ClipboardCapture Image(byte[] png, string? source, DateTimeOffset createdAt)
        => new(ClipboardCaptureKind.Image, null, null, png, source, createdAt);
}

internal enum ClipboardCaptureKind
{
    Files,
    Text,
    Image
}

internal sealed record ProcessedClipboardCapture(ClipboardHistoryItem Item, byte[]? OriginalImage);

internal static class NativeMethods
{
    [System.Runtime.InteropServices.DllImport("user32.dll")]
    internal static extern IntPtr GetForegroundWindow();

    [System.Runtime.InteropServices.DllImport("user32.dll")]
    internal static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint processId);
}

internal static class ListExtensions
{
    public static IEnumerable<int> Indices<T>(this IReadOnlyList<T> list)
    {
        return Enumerable.Range(0, list.Count);
    }
}

internal static class DictionaryExtensions
{
    public static async Task<TValue> GetOrAdd<TKey, TValue>(
        this Dictionary<TKey, Task<TValue>> dictionary,
        TKey key,
        Func<TKey, Task<TValue>> factory)
        where TKey : notnull
    {
        if (dictionary.TryGetValue(key, out var existing))
        {
            return await existing;
        }

        var created = factory(key);
        dictionary[key] = created;
        return await created;
    }
}
